
title: My Resume
url: 'https://zubairashfaque.github.io/'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Zubair Ashfaque  ## put your name
title: 'Data Scientist &amp; Machine Learning Engineer'  ## your title
location: Lahore, Pakistan


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
